//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfEntityMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDictionary
    {
        public string Code { get; set; }
        public string DictionaryName { get; set; }
        public string ParentCode { get; set; }
        public string ParentName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Remart { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
