//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySelfEntityMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNews
    {
        public System.Guid Id { get; set; }
        public string NewsName { get; set; }
        public string NewsContent { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
